### ISSUE TITLE
Space listing page at /space/:space_id endpoint

### ISSUE THREAD

**Issue by Jonathan6** [jmichaelbrown8/elevator-pitch#10] opened 2022-03-02 17:23 UTC

**Comment by jmichaelbrown8** [comment] 2022-03-03 06:01
Let's double check that this isn't a duplicate of what Kim's working on in: https://github.com/jmichaelbrown8/elevator-pitch/pull/14

**Comment by kimberlym4488** [comment] 2022-03-03 19:10
> Let's double check that this isn't a duplicate of what Kim's working on in: #14
All set!

**Closed** 2022-03-11 06:22 UTC
